services:
  bracket-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - ./bracket-tournament:/app/bracket-tournament
    environment:
      - PORT=3000